version: '3.8'

services:
  app:
    image: go-remote-code
    environment:
      - PORT=3000
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    ports:
      - "8080:3000"
    networks:
      - pentester

networks:
  pentester:
    external: true
